#!/bin/csh
cd /cs/casmip/nirm/embryo_project_version1/venu-pytorch/bin
source activate.csh
cd /cs/casmip/nirm/embryo_project_version1/embyo_projects_codes/lord-pytorch-unet
#python3 lord_unet.py --base-dir /cs/casmip/nirm/embryo_project_version1/embryo_data preprocess --dataset-id embryo_dataset --dataset-path /cs/casmip/nirm/embryo_project_version1/DATA3D --data-name embryo_data3d_1 --jumps 1
#python3 lord_unet.py --base-dir /cs/casmip/nirm/embryo_project_version1/embryo_data train_ulord --data-l-name embryo_data_2_labeled_1 --data-u-name embryo_data_2_ulabled_1 --model-name ulord_model_2_0t --load-model 0 --seg-loss 1 --seg-gard 1 --recon-loss 1 --r-content 0 --r-rclass 0
#python3 lord_unet.py  --base-dir /cs/casmip/nirm/embryo_project_version1/embryo_data train_ulord --data-l-name embryo_data_1_labeled_1 --data-u-name embryo_data_1_ulabled_1 --model-name ulord_model_1_1 --load-model 0 --seg-loss 1 --seg-gard 1 --recon-loss 1 --r-content 0 --r-rclass 0
#python3 lord_unet.py  --base-dir /cs/casmip/nirm/embryo_project_version1/embryo_data train_ulord --data-l-name embryo_data_1_labeled_2 --data-u-name embryo_data_1_ulabled_2 --model-name ulord_model_1_2 --load-model 0 --seg-loss 1 --seg-gard 1 --recon-loss 1 --r-content 0 --r-rclass 0
#python3 lord_unet.py  --base-dir /cs/casmip/nirm/embryo_project_version1/embryo_data train_ulord --data-l-name embryo_data_1_labeled_3 --data-u-name embryo_data_1_ulabled_3 --model-name ulord_model_1_3 --load-model 0 --seg-loss 1 --seg-gard 1 --recon-loss 1 --r-content 0 --r-rclass 0
#python3 lord_unet.py --base-dir /cs/casmip/nirm/embryo_project_version1/embryo_data split-samples-ulord --input-data-name embryo_data3d_1 --labled-data-name embryo_data3d_1_labeled_1 --ulabled-data-name embryo_data3d_1_ulabled_1 --f-split 1 --t-split 0.1
#python3 lord_unet.py --base-dir /cs/casmip/nirm/embryo_project_version1/embryo_data split-samples-ulord --input-data-name embryo_data3d_1 --labled-data-name embryo_data3d_1_labeled_2 --ulabled-data-name embryo_data3d_1_ulabled_2 --f-split 1 --t-split 0.2
#python3 lord_unet.py --base-dir /cs/casmip/nirm/embryo_project_version1/embryo_data split-samples-ulord --input-data-name embryo_data3d_1 --labled-data-name embryo_data3d_1_labeled_3 --ulabled-data-name embryo_data3d_1_ulabled_3 --f-split 1 --t-split 0.3
#python3 lord_unet.py --base-dir /cs/casmip/nirm/embryo_project_version1/embryo_data train_unet3D --data-l-name embryo_dataset_train_l --data-v-name embryo_dataset_val --model-name unet3d_model --load-model 0 --g-config 0 --p-config '' --p-uconfig ''
#python3 lord_unet.py --base-dir /cs/casmip/nirm/embryo_project_version1/embryo_data train_unet3D --data-l-name e
#
python3 lord_unet.py --base-dir /cs/casmip/nirm/embryo_project_version1/embryo_data train_unet3D --data-l-name embryo_dataset_train_l --data-v-name embryo_dataset_val --model-name unet3d_model_lr_4_sf_2 --load-model 0 --g-config 1 --p-config /cs/casmip/nirm/embryo_project_version1/config_for_many_run_U/lr_4_sf_2/ --p-uconfig /cs/casmip/nirm/embryo_project_version1/config_for_many_run_U/lr_4_sf_2/
python3 lord_unet.py --base-dir /cs/casmip/nirm/embryo_project_version1/embryo_data train_unet3D --data-l-name embryo_dataset_train_l --data-v-name embryo_dataset_val --model-name unet3d_model_lr_4_sf_4 --load-model 0 --g-config 1 --p-config /cs/casmip/nirm/embryo_project_version1/config_for_many_run_U/lr_4_sf_4/ --p-uconfig /cs/casmip/nirm/embryo_project_version1/config_for_many_run_U/lr_4_sf_4/
python3 lord_unet.py --base-dir /cs/casmip/nirm/embryo_project_version1/embryo_data train_unet3D --data-l-name embryo_dataset_train_l --data-v-name embryo_dataset_val --model-name unet3d_model__lr_4_sf_8 --load-model 0 --g-config 1 --p-config /cs/casmip/nirm/embryo_project_version1/config_for_many_run_U/lr_4_sf_8/ --p-uconfig /cs/casmip/nirm/embryo_project_version1/config_for_many_run_U/lr_4_sf_8/

python3 lord_unet.py --base-dir /cs/casmip/nirm/embryo_project_version1/embryo_data train_unet3D --data-l-name embryo_dataset_train_l --data-v-name embryo_dataset_val --model-name unet3d_model_lr_5_sf_2  --load-model 0 --g-config 1 --p-config /cs/casmip/nirm/embryo_project_version1/config_for_many_run_U/lr_5_sf_2/ --p-uconfig /cs/casmip/nirm/embryo_project_version1/config_for_many_run_U/lr_5_sf_2/
python3 lord_unet.py --base-dir /cs/casmip/nirm/embryo_project_version1/embryo_data train_unet3D --data-l-name embryo_dataset_train_l --data-v-name embryo_dataset_val --model-name unet3d_model_lr_5_sf_4 --load-model 0--g-config 1 --p-config /cs/casmip/nirm/embryo_project_version1/cconfig_for_many_run_U/lr_5_sf_4/ --p-uconfig /cs/casmip/nirm/embryo_project_version1/config_for_many_run_U/lr_5_sf_4/
python3 lord_unet.py --base-dir /cs/casmip/nirm/embryo_project_version1/embryo_data train_unet3D --data-l-name embryo_dataset_train_l --data-v-name embryo_dataset_val --model-name unet3d_model_lr_5_sf_8 --load-model 0 --g-config 1 --p-config /cs/casmip/nirm/embryo_project_version1/config_for_many_run_U/lr_5_sf_8/ --p-uconfig /cs/casmip/nirm/embryo_project_version1/config_for_many_run_U/lr_5_sf_8/
#
#python3 lord_unet.py --base-dir /cs/casmip/nirm/embryo_project_version1/embryo_data train_unet3D --data-l-name embryo_dataset_train_l --data-v-name embryo_dataset_val --model-name unet3d_model --load-model 0 --g-config 1 --p-config /cs/casmip/nirm/embryo_project_version1/config_for_many_run_U/lr_6_sf_2/ --p-uconfig /cs/casmip/nirm/embryo_project_version1/config_for_many_run_U/lr_6_sf_2/
#python3 lord_unet.py --base-dir /cs/casmip/nirm/embryo_project_version1/embryo_data train_unet3D --data-l-name embryo_dataset_train_l --data-v-name embryo_dataset_val --model-name unet3d_model --load-model 0 --g-config 1 --p-config /cs/casmip/nirm/embryo_project_version1/config_for_many_run_U/lr_6_sf_4/ --p-uconfig /cs/casmip/nirm/embryo_project_version1/config_for_many_run_U/lr_6_sf_4/
#python3 lord_unet.py --base-dir /cs/casmip/nirm/embryo_project_version1/embryo_data train_unet3D --data-l-name embryo_dataset_train_l --data-v-name embryo_dataset_val --model-name unet3d_model --load-model 0 --g-config 1 --p-config /cs/casmip/nirm/embryo_project_version1/config_for_many_run_U/lr_6_sf_8/ --p-uconfig /cs/casmip/nirm/embryo_project_version1/config_for_many_run_U/lr_6_sf_8/
